### PR TITLE
Fix FlowPart view which uses the AdditionalStylingPart 

### LINKED ISSUE #35: Flows Helpful Extensions - AdditionalStylingPart does not add the widget classes
Hello Lombiq team,

I am using the Flows Helpful Extensions feature, and I realized when this feature is enabled and there were content items with widgets already created, thus these content items do not have the AdditionalStylingPart yet, so the classes `widget` and `widget-{ContentType}` are not added, and the widgets are rendered incorrectly in the view without those classes. 

One solution is to re-publish the content items so they become aware of the `AdditionalStylingPart` and render correctly, but in an existing site with many content items, this solution does not seem reasonable.

For now, I made a little change in the view `Lombiq.HelpfulExtensions.Flows.FlowPart.cshtml` trying to follow the original logic to solve this issue. I already tested it in the [Open-Source-Orchard-Core-Extensions](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions) solution and in my own project, and it is working well. You can check it out [here in this fork repo](https://github.com/AntonySandoval/Helpful-Extensions/blob/issue/fix-flows-helpful-extensions/Views/Lombiq.HelpfulExtensions.Flows.FlowPart.cshtml) and please let me know if you have any comment or suggestion on it, or if there is another better solution to go for. I would be glad to contribute to the solution and create a pull request if it suits you well and you consider it that way.

### PR DESCRIPTION
**Pull request by AntonySandoval**
Flows Helpful Extension:
* Fixed AdditionalStylingPart for FlowPart to render the widgets correctly.

Fixes #35.

### CODE REVIEW

**Comment by Piedone** [comment]
Thank you, looks good. Would you venture into fixing the editor part of this too? When you edit an item that existed before turning on the feature you won't see this editor:
image

**Comment by AntonySandoval** [comment]
Ok, I'll check that issue to figure out what is happening, and see how I can solve it too.

**Comment by Piedone** [comment]
Are you ready for another review?

**Comment by AntonySandoval** [comment]
Yes, I am. I tested the new commit and it is working well. Could you please review the new changes? And if everything is ok and you consider that nothing else is missing, you can complete de PR.

**Comment by Piedone** [comment]
Looks great, thank you!

**Pull request merged**
